config/routes.rb
Rails.application.routes.draw do

# static_pages
root 'static_pages#home'
get '/welcome', to: 'static_pages#welcome'

# users
get '/signup',  to: 'users#new'
post '/signup', to: 'users#create'

# session
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'

# communities
get '/communities', to: 'communities#index'

resources :communities do
  get 'events', on: :member, to: 'events#new'
  post 'events', on: :member, to: 'events#create'
end

# eventsのidを取得する。

resources :events, except: [:new, :create]
resources :profiles
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :events
  mount_uploader :picture, PictureUploader
  # has_many :category
  # has_many :category, through: :category_community
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :community
  mount_uploader :picture, PictureUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
   belongs_to :user
   mount_uploader :picture, PictureUploader
   validate  :picture_size

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_many :communities, dependent: :destroy
  has_many :events, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true,length: { maximum: 50 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,length: { maximum: 255 },
                    format: { with:VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  #セキュアなパスワードを追加
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index
    @communities = Community.all
  end

  def new
    @community = Community.new
  end

  def show
    # @community = findcurrent_user.communities.build(community_params)
    @community = Community.find(params[:id])
    @events = Event.where(community_id: @community.id)
  end

  def create
    #ユーザに紐付いてコミュニティを作成する。
    @community = current_user.communities.build(community_params)
    if @community.save
      #ユーザ登録が成功した時点で@community_commnetも作成する
      # @profile = Profile.new(user_id: @user.id).save
      redirect_to @community
    else
      render 'delete'
    end
  end

  def edit
    @community = current_user.communities.find(params[:id])
  end

  def update
    @community = current_user.communities.find(params[:id])
    if @community.update_attributes(community_params)
    #登録成功時の処理
      redirect_to @community
    else
      render 'index'
    end
  end

  def delete
  end

  private

    def community_params
      params.require(:community).permit(:name, :content, :category,
                                   :admin_allowed,:picture)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @community = current_user.communities.find(params[:id])
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end


  def edit
    @event = Event.find(params[:id])
  end


  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      #登録成功時の処理
      redirect_to @event
    else
      redirect_to 'edit'
    end
  end

  def create
    @community = current_user.communities.find(params[:id])
    @event = current_user.events.build(event_params)
    @event.community_id = @community.id
    #ユーザidとコミュニティidに紐付いてコミュニティを作成する。
    if @event.save
      #ユーザ登録が成功した時点で@community_commnetも作成する
      # @profile = Profile.new(user_id: @user.id).save
      redirect_to @event
    else
      render 'delete'
    end
  end

  def delete
  end

  private
    def event_params
      params.require(:event).permit(:name, :date, :location,
                                    :money, :content, :picture)
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
    #登録成功時の処理
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def delete
  end

  private

    def profile_params
      params.require(:profile).permit(:gallery_name, :hp, :tw_id,
                                      :insta_id,:content, :picture)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # emailに該当するユーザをみつける
    user = User.find_by(email: params[:session][:email].downcase)
    # ユーザーがデータベースにあり、かつ、認証に成功した
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to  communities_path
    else
      flash[:danger] = 'emailもしくはpasswordが正しくありません'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def welcome
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      @profile = Profile.create(user_id:@user.id)
      
      log_in @user
      redirect_to '/welcome'
    else
      render 'new'
    end
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
   end

   # beforeアクション

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
   session[:user_id] = user.id
  end

  def current_user
    # @current_userの値がnilなら変数に代入するが、nilでなければ代入しない
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
   !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/delete.html.erb
<h1>Communities#delete</h1>
<p>Find me in app/views/communities/delete.html.erb</p>

app/views/communities/edit.html.erb
<% provide(:title, @community.user.name) %>
<head>
    <meta name="viewport" content="user-scalable=no" />
</head>
<body class="community-new">
  <h1 class="community-new-title">コミュニティ編集</h1>
  <div>
    <%= form_for(@community) do |f| %>
    <!-- <div class="choose-photo">写真</div> -->

    <div class="choose-photo commu-photo comu-cen">
      <%= image_tag @community.picture.url if @community.picture? %>
    </div>

    <span class="picture">
      <%= f.file_field :picture %>
    </span>

    <ul>
      <!-- <li class="">
        <%= @community.user.name %>
      </li> -->
      <li class="community-new-items">
        <%= f.label :name,"コミュニティ名", class: "communityNew-name" %>
        <%= f.text_field :name, class: "communityNew-name-text"%>
      </li>
      <li class="community-new-items">
        <%= f.label :category,"カテゴリ", class: "communityNew-name communityNew-category-choose" %>
        <%= f.select :category, [ ["アクセサリー", "アクセサリー"], ["ファッション", "ファッション"], ["雑貨", "雑貨"], ["素材","素材"], ["その他", "その他"] ], class: "communityNew-category-choose" %>
      </li>
      <li class="community-new-items">
        <%= f.label :content,"コミュニティの説明", class: "communityNew-name community-intro" %>
        <%= f.text_area :content, class: "communityNew-name-text commu-intro"%>
      </li>

      <p class="communityNew-name community-new-items chose">以下どちらかを選択して下さい。</p>
      <li class="community-new-items">
          <%= f.radio_button :admin_allowed, false , checked: true %>
          <%= f.label :admin_allowed, "コミュニティメンバーであれば誰でもイベントを作れるようにする", class: "choose-open-close" %>
      </li>
      <li class="community-new-items close">
          <%= f.radio_button :admin_allowed, true, checked: false %>
          <%= f.label :admin_allowed, "あなたしかイベントを作成できないようにする", class: "choose-open-close" %>
      </li>

      <%= f.submit "編集完了!", class: "profileForm__submit", id: "commu" %>
    </ul>
    <% end %>
  </div>
</body>

app/views/communities/index.html.erb
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<div class="community-index">
  <div class="communityHeader">
    <h1 class="go-to-top">
      <%= link_to '', communities_path %>
    </h1>

    <!-- 検索 -->
    <!-- <div class="serch">
      <%= form_tag(users_path, method:"get") do%>
      <%= text_field_tag :name, params[:name], class: "serch-text" %>
      <%= submit_tag "検索" , class: "serch-submit"%>
      <% end %>
    </div> -->

    <div class="serch">
      <div class="icon-search-container" data-ic-class="search-trigger">
        <span class="fa fa-search"></span>
        <input type="text" class="search-input serch-text" data-ic-class="search-input" placeholder="検索"/>
        <span class="fa fa-times-circle" data-ic-class="search-clear"></span>
      </div>
    </div>
    <!-- アイコン -->
    <div class="profileIcon">
      <label class="profileIcon__items" for="Panel1">アイコン</label>
          <input type="checkbox" id="Panel1" class="on-off" />
          <%= render 'shared/header' %>
    </div>
  </div>

  <!-- カテゴリー -->
  <div class="categoriesItems">
    <ul class="categories">
      <li class="category"><a href="#">すべて</a></li>
      <li class="category"><a href="#">アクセサリー</a></li>
      <li class="category"><a href="#">ファッション</a></li>
      <li class="category"><a href="#">雑貨</a></li>
      <li class="category"><a href="#">素材</a></li>
      <li class="category"><a href="#">その他</a></li>
    </ul>
  </div>


  <!-- コミュニティ一覧 -->
  <div class="communities-wrapper">
    <h2>すべて</h2>
      <ul class="communities">
        <% @communities.each do |community| %>
        <li class="community">
          <div class="communityImage">
            <%= link_to image_tag community.picture.url if community.picture? %>
          </div>
          <h3><%= link_to community.name, community %></h3>
        </li>
        <% end %>
      </ul>
  </div>


  <!-- コミュニティ作成ボタン -->
  <%= link_to "", new_community_path, class: "createCommunityBtn" %>
</div>

app/views/communities/new.html.erb
<% provide(:title, "コミュニティ作成ページ") %>
<head>
    <meta name="viewport" content="user-scalable=no" />
</head>
<body class="community-new">
  <h1 class="community-new-title">コミュニティ作成</h1>

  <div>
    <%= form_for(@community) do |f| %>
    <span class="picture">
      <%= f.file_field :picture %>
    </span>

    <ul class="">
      <li class="community-new-items">
        <%= f.label :name,"コミュニティ名", class: "communityNew-name" %>
        <%= f.text_field :name, :class => "communityNew-name-text" %>
      </li>
      <li class="community-new-items">
        <%= f.label :category,"カテゴリ", class: "communityNew-name communityNew-category-choose" %>
        <%= f.select :category, [ ["アクセサリー", "アクセサリー"], ["ファッション", "ファッション"], ["雑貨", "雑化"], ["素材","素材"], ["その他", "その他"] ], class: "communityNew-category-choose" %>
      </li>
      <li class="community-new-items">
        <%= f.label :content,"コミュニティの説明", class: "communityNew-name community-intro" %>
        <%= f.text_area :content, :class => "communityNew-name-text commu-intro" %>
      </li>
      <p class="communityNew-name community-new-items chose">以下どちらかを選択して下さい。</p>
      <li class="community-new-items">
          <%= f.radio_button :admin_allowed, false , checked: true%>
          <%= f.label :admin_allowed, "コミュニティメンバーであれば誰でもイベントを作れるようにする", class: "choose-open-close" %>
      </li>
      <li class="community-new-items close">
          <%= f.radio_button :admin_allowed, true %>
          <%= f.label :admin_allowed, "あなたしかイベントを作成できないようにする", class: "choose-open-close" %>
      </li>
      <%= f.submit "コミュニティを作成", class: "profileForm__submit", id: "commu"%>
    </ul>
    <% end %>
  </div>
</body>

app/views/communities/show.html.erb
<% provide(:title,@community.name) %>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="communityBody">
  <div class="profile-header">
    <h1 class="go-to-top">
      <%= link_to '', communities_path, class: 'to-top' %>
    </h1>
    <%= link_to edit_community_path(@community.id) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </div>

  <div class="choose-photo commu-photo comu-cen">
    <%= image_tag @community.picture.url if @community.picture? %>
  </div>

  <div class="community-show">
    <h2 class="community-show-name"> <%= @community.name %> </h2>

    <h3 class="community-show-title">設立者</h3>
    <p class="community-show-text"><%= @community.user.name %><p>

    <h3 class="community-show-title">カテゴリ</h3>
    <p class="community-show-text"><%= @community.category %><p>

    <h3 class="community-show-title">このコミュニティについて</h3>
    <p class="community-show-text"><%= @community.content %></p>

    <h3 class="community-show-title">イベント作成について</h3>
    <% if @community.admin_allowed %>
      <p class="community-show-text">管理者しかイベントを作成する事ができないです。</p>
    <% else %>
      <p class="community-show-text">誰でも自由にイベントを作成する事ができます</p>
    <% end %>

    <h3 class="community-show-title">開催イベント</h3>

    <!-- イベント覧 -->
    <div class="">
        <ul class="">
          <li>
            <%= link_to "イベントを作成", events_community_path, class: "create-event" %>
          </li>
          <% @events.each do |event| %>
          <li class="">
            <div class="">
              <%= link_to image_tag event.picture.url if event.picture? %>
            </div>
            <h3><%= link_to event.name, event %></h3>
          </li>
          <% end %>
        </ul>
    </div>

    <!-- <%= link_to "イベントを作成", events_community_path, class: "create-event" %> -->
  </div>

  </div>
</body>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<head>
    <meta name="viewport" content="user-scalable=no" />
</head>
<body class="community-new">
  <h1 class="community-new-title">イベント編集</h1>
  <div>
    <%= form_for(@event) do |f| %>
    <span class="picture">
      <%= f.file_field :picture %>
    </span>
    <ul>
      <li class="community-new-items">
        <%# ここは編集しない。 %>
      </li>
      <li class="community-new-items">
        <%= f.label :name,"イベント名", class: "communityNew-name" %>
        <%= f.text_field :name, class: "communityNew-name-text"%>
      </li>
      <li class="community-new-items">
        <%= f.label :date,"開催日時", class: "communityNew-name" %>
        <div class="time">
          <%= f.datetime_select :date, :class => "communityNew-name-text time-choose" %>
        </div>
      </li>
      <li class="community-new-items">
        <%= f.label :location,"開催場所", class: "communityNew-name" %>
        <%= f.text_field :location, class: "communityNew-name-text"%>
      </li>
      <li class="community-new-items">
        <%= f.label :money,"費用", class: "communityNew-name" %>
        <%= f.text_field :money, class: "communityNew-name-text"%>
      </li>
      <li class="community-new-items">
        <%= f.label :content,"このイベントについて", class: "communityNew-name" %>
        <%= f.text_area :content, class: "communityNew-name-text"%>
      </li>
      <%= f.submit "編集完了!", class: "profileForm__submit", id: "commu" %>
    </ul>
    <% end %>
  </div>
</body>

app/views/events/new.html.erb
<!-- <p>イベント設立者:<%= @community.user.name %></p>
<p>コミュニティ:<%= @community.name %></p> -->
<head>
    <meta name="viewport" content="user-scalable=no" />
</head>
<body class="community-new">
  <h1 class="community-new-title">イベント作成</h1>

  <div>
    <%= form_for(@event, url: events_community_path) do |f| %>
    <!-- <div class="choose-photo">写真</div> -->
    <span class="picture">
      <%= f.file_field :picture %>
    </span>


    <ul class="">
      <li  class="community-new-items">
        <%= f.label :name,"イベント名", class: "communityNew-name" %>
        <%= f.text_area :name, :class => "communityNew-name-text" %>
      </li>
      <li  class="community-new-items">
        <%= f.label :date,"開催日時", class: "communityNew-name" %>
        <div class="time">
          <%= f.datetime_select :date, :class => "communityNew-name-text time-choose" %>
        </div>
      </li>
      <li  class="community-new-items">
        <%= f.label :location,"開催場所", class: "communityNew-name" %>
        <%= f.text_area :location, :class => "communityNew-name-text" %>
      </li>
      <li  class="community-new-items">
        <%= f.label :money,"費用", class: "communityNew-name" %>
        <%= f.text_area :money, :class => "communityNew-name-text" %>
      </li>
      <li  class="community-new-items">
        <%= f.label :content,"イベント詳細", class: "communityNew-name" %>
        <%= f.text_field :content, :class => "communityNew-name-text" %>
      </li>
      <%= f.submit "イベントを作成する", class: "profileForm__submit", id: "commu"%>
    </ul>
    <% end %>
  </div>
</body>

app/views/events/show.html.erb
<% provide(:title,@event.name) %>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="communityBody">
  <div class="profile-header">
    <h1 class="go-to-top">
      <%= link_to '', communities_path, class: 'to-top' %>
    </h1>
    <%= link_to edit_event_path(@event.id) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </div>

  <div class="choose-photo commu-photo comu-cen">
    <%= image_tag @event.picture.url if @event.picture? %>
  </div>

  <div class="community-show">
    <h2 class="community-show-name"> <%= @event.name %> </h2>

    <h3 class="community-show-title">設立者</h3>
    <p class="community-show-text"><%= @event.user.name %><p>

    <h3 class="community-show-title">詳細</h3>
    <ul class="event-details">
      <%# 場所 %>
      <li class="event-detail"><i class="fa fa-map-marker" aria-hidden="true"></i>　<%= @event.location %></li>
      <%# 日時 %>
      <li class="event-detail"><i class="fa fa-clock-o" aria-hidden="true"></i>　<%= @event.date %></li>
      <%# お金 %>
      <li class="event-detail"><i class="fa fa-jpy" aria-hidden="true"></i>　<%= @event.money %></li>
    </ul>

    <h3 class="community-show-title">このイベントについて</h3>
    <p class="community-show-text"><%= @event.content %></p>

    <h3><%= link_to "コミュニティに戻る", @event.community %></h3>


  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OsanDev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# jquery %>
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous">
    </script>
  </head>

  <body>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/profiles/delete.html.erb
<h1>Profiles#delete</h1>
<p>Find me in app/views/profiles/delete.html.erb</p>

app/views/profiles/show.html.erb
<% provide(:title, @profile.user.name) %>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body class="profile">
  <div class="profileEdit">
    <div class="profile-header">
      <h1 class="go-to-top2">
        <%= link_to '', communities_path, class: 'to-top' %>
      </h1>
      <%= link_to(content_tag(:i, '', class: 'fa fa-pencil'), edit_profile_path) %>
    </div>
    <!-- <li> -->
      <!-- <div class="profileForm__picWindow">+</div> -->
      <!-- <label for="pic-choose-btn" class="pic-choose-label">
        <svg id="レイヤー_1" class="plus-svg" data-name="レイヤー 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 169 169"><defs><style>.cls-1{fill:none;stroke:#fff;stroke-miterlimit:10;stroke-width:5px;}</style></defs><title>plus</title><line class="cls-1" y1="84.5" x2="169" y2="84.5"/><line class="cls-1" x1="84.5" x2="84.5" y2="169"/></svg>
      </label> -->
    <!-- </li> -->

    <div class="profilePic">
      <%= image_tag @profile.picture.url if @profile.picture? %>
    </div>

    <div class="userName">
      <%= @profile.user.name %>
    </div>

    <div class="profilePad">
      <ul class="profile-items">
        <li class="gallery_name profile-item">
          <h2 class="profileTitle">ギャラリーネーム</h2>
          <% if @profile.gallery_name? %>
            <p class="profileText"><%= @profile.gallery_name %></p>
          <% else %>
            <p class="profileText">まだ入力されてません</p>
          <% end %>
        </li>
        <li class="introduction profile-item">
          <h2 class="profileTitle">自己紹介</h2>
          <% if  @profile.content? %>
            <p class="profileText"><%= @profile.content %></p>
          <% else %>
            <p class="profileText">まだ入力されてません</p>
          <% end %>
        </li>
        <li class="homepage profile-item">
          <h2 class="profileTitle">ホームページ</h2>
          <% if  @profile.hp? %>
            <p class="profileText"><a href="<%= @profile.hp %>"><%= @profile.hp %></a></p>
          <% else %>
            <p class="profileText">まだ入力されてません</p>
          <% end %>
        </li>
      </ul>

        <ul class="sns-icons">
          <li class="sns-icon twitter">
              <% if  @profile.tw_id? %>
              <a href="https://twitter.com/<%= @profile.tw_id %>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <% end %>
          </li>
          <li class="sns-icon insta">
              <% if  @profile.insta_id? %>
              <a href="https://www.instagram.com/<%= @profile.tw_id %>"><i class="fa fa-instagram" aria-hidden="true"></i></a>
              <% end %>
          </li>
        </ul>
    </div>

  </div>
</body>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <ul class="error-message-wrapper">
    <% @user.errors.full_messages.each do |msg| %>
      <li class="error-message"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<ul>
  <% if logged_in? %>
    <li><%= link_to "Profile", profile_path(current_user) %></li>
    <li><%= link_to "Log out", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log in", login_path %></li>
  <% end %>
</ul>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hold Hands</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body class="welcomePage">
    <div class="welcomeTop">
      <h1 class="welcomeTop__title">
        <%= image_tag 'hold-hands-logo.svg' %>
      </h1>
      <p class="welcomeTop__intro">
        ハンドメイド好きの、ハンドメイド好きによる<br>
        ハンドメイド好きのためのサービス
      </p>
    </div>

    <div class="welcomeBtns">
      <span class="welcomeBtns__signUp">
        <%= link_to 'サインアップ', 'signup' %>
      </span>
      <span class="welcomeBtns__logIn">
        <%= link_to 'ログイン', 'login' %>
      </span>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<head>
    <meta name="viewport" content="user-scalable=no" />
</head>
<body class="welcomePage">
  <div class="welcomeTop">
    <h1 class="welcomeTop__title">
      <%= image_tag 'hold-hands-logo.svg' %>
    </h1>
  </div>
  <div class="signupPage">
    <%= form_for(@user,url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

    <ul class="signupPage__inputs">
      <li>
        <%= f.email_field :email, :placeholder => "Eメール", :class => "signupPage__inside signupPage__inside--email" %>
      </li>
      <li>
        <%= f.password_field :password,:placeholder => "パスワード", :class => "signupPage__inside signupPage__inside--password" %>
      </li>
      <li>
        <%= f.password_field :password_confirmation,:placeholder => "パスワード(確認)", :class => "signupPage__inside signupPage__inside--password" %>
      </li>
      <li>
        <%= f.text_field :name, :placeholder => "ユーザネーム", :class => "signupPage__inside signupPage__inside--name" %>
      </li>
      <%= f.submit "完了", class: "signupBtn"%>
    </ul>
    <% end %>
  </div>
</div>